# Generated by Django 2.2.7 on 2019-12-22 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 11, 6, 33, 935756, tzinfo=utc)),
        ),
    ]
