# Generated by Django 2.2.7 on 2019-12-24 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191224_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 24, 20, 9, 3, 653917, tzinfo=utc)),
        ),
    ]
