# Generated by Django 2.2.7 on 2019-12-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20191222_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='travel_mode',
            field=models.CharField(choices=[('DRIVING', 'Driving'), ('BICYCLING', 'Biking'), ('TRANSIT', 'Transit'), ('WALKING', 'Walking')], default='DRIVING', max_length=50),
        ),
    ]
